env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
  "react/prop-types": "off",
  "react/display-name": "off",
  "react/no-unescaped-entities": "off",
  "no-console": "warn",
  "no-unused-vars": "error",
  "quotes": ["warn", "double"],
  "prefer-const": "error",
  "indent": ["warn", 4],
  "max-len": ["warn", {"code": 160}],
  "comma-dangle": ["error", "never"],
  "semi": ["warn", "always"]
}
