import { IExchanges } from "../../types/coins.types";

export const tempExchanges: IExchanges[] = [
    {
        id: "binance",
        name: "Binance",
        year_established: 2017,
        country: "Cayman Islands",
        description: "",
        url: "https://www.binance.com/",
        image: "https://assets.coingecko.com/markets/images/52/small/binance.jpg?1706864274",
        has_trading_incentive: false,
        trust_score: 10,
        trust_score_rank: 1,
        trade_volume_24h_btc: 356686.4158202145,
        trade_volume_24h_btc_normalized: 194545.06187147464
    },
    {
        id: "bybit_spot",
        name: "Bybit",
        year_established: 2018,
        country: "British Virgin Islands",
        description:
            "Bybit is a cryptocurrency exchange that offers a professional platform featuring an ultra-fast matching engine, excellent customer service and multilingual community support for crypto traders of all levels. Established in March 2018, Bybit currently serves more than 10 million users and institutions offering access to over 100 assets and contracts across Spot, Futures and Options, launchpad projects, earn products, an NFT Marketplace and more. Bybit is a proud partner of Formula One racing team, Oracle Red Bull Racing, esports teams NAVI, Astralis, Alliance, Virtus.pro, Made in Brazil (MIBR), City Esports, and Oracle Red Bull Racing Esports, and association football (soccer) teams Borussia Dortmund and Avispa Fukuoka.",
        url: "https://www.bybit.com",
        image: "https://assets.coingecko.com/markets/images/698/small/bybit_spot.png?1706864649",
        has_trading_incentive: false,
        trust_score: 10,
        trust_score_rank: 2,
        trade_volume_24h_btc: 63131.899805674904,
        trade_volume_24h_btc_normalized: 63131.899805674904
    },
    {
        id: "gdax",
        name: "Coinbase Exchange",
        year_established: 2012,
        country: "United States",
        description: "",
        url: "https://www.coinbase.com/",
        image: "https://assets.coingecko.com/markets/images/23/small/Coinbase_Coin_Primary.png?1706864258",
        has_trading_incentive: false,
        trust_score: 10,
        trust_score_rank: 3,
        trade_volume_24h_btc: 44800.14051979858,
        trade_volume_24h_btc_normalized: 44800.14051979858
    },
    {
        id: "huobi",
        name: "HTX",
        year_established: 2013,
        country: "Seychelles",
        description: "",
        url: "https://www.huobi.com",
        image: "https://assets.coingecko.com/markets/images/25/small/logo_V_colour_black.png?1706864260",
        has_trading_incentive: false,
        trust_score: 10,
        trust_score_rank: 4,
        trade_volume_24h_btc: 33145.87771278582,
        trade_volume_24h_btc_normalized: 33145.87771278582
    },
    {
        id: "kraken",
        name: "Kraken",
        year_established: 2011,
        country: "United States",
        description: "",
        url: "https://www.kraken.com/",
        image: "https://assets.coingecko.com/markets/images/29/small/kraken.jpg?1706864265",
        has_trading_incentive: false,
        trust_score: 10,
        trust_score_rank: 5,
        trade_volume_24h_btc: 17383.879172787005,
        trade_volume_24h_btc_normalized: 17383.879172787005
    },
    {
        id: "kucoin",
        name: "KuCoin",
        year_established: 2017,
        country: "Seychelles",
        description:
            "Launched in September 2017, KuCoin is a global cryptocurrency exchange with its operational headquarters in Seychelles. As a user-oriented platform with a focus on inclusiveness and community action reach, it offers over 800 digital assets and currently provides Spot trading, Margin trading, P2P Fiat trading, Futures trading, Staking, and Lending to its 30 million users in more than 200 countries and regions. KuCoin is currently one of the top 5 crypto exchanges. In 2023, KuCoin was named one of the Best Crypto Exchanges by Forbes and recognized as a highly commended global exchange in Finder's 2023 Global Cryptocurrency Trading Platform Awards. Learn more at https://www.kucoin.com.",
        url: "https://www.kucoin.com/",
        image: "https://assets.coingecko.com/markets/images/61/small/kucoin.png?1706864282",
        has_trading_incentive: false,
        trust_score: 10,
        trust_score_rank: 6,
        trade_volume_24h_btc: 15329.513973580457,
        trade_volume_24h_btc_normalized: 15329.513973580457
    },
    {
        id: "crypto_com",
        name: "Crypto.com Exchange",
        year_established: 2019,
        country: "Malta",
        description:
            "Crypto.com Exchange is the best place to trade crypto, with deep liquidity, low fees and best execution prices, users can trade major cryptocurrencies like Bitcoin, Ethereum, and many more and receive great CRO-powered rewards",
        url: "https://crypto.com/exchange",
        image: "https://assets.coingecko.com/markets/images/589/small/h2oMjPp6_400x400.jpg?1706864542",
        has_trading_incentive: false,
        trust_score: 10,
        trust_score_rank: 7,
        trade_volume_24h_btc: 22831.27616625528,
        trade_volume_24h_btc_normalized: 11997.625253986693
    },
    {
        id: "binance_us",
        name: "Binance US",
        year_established: 2019,
        country: "United States",
        description: "",
        url: "https://www.binance.us/",
        image: "https://assets.coingecko.com/markets/images/469/small/Binance.png?1706864454",
        has_trading_incentive: false,
        trust_score: 10,
        trust_score_rank: 8,
        trade_volume_24h_btc: 301.4113610847222,
        trade_volume_24h_btc_normalized: 301.4113610847222
    },
    {
        id: "okex",
        name: "OKX",
        year_established: 2017,
        country: "Seychelles",
        description: "",
        url: "https://www.okx.com",
        image: "https://assets.coingecko.com/markets/images/96/small/WeChat_Image_20220117220452.png?1706864283",
        has_trading_incentive: false,
        trust_score: 9,
        trust_score_rank: 9,
        trade_volume_24h_btc: 50522.147736741616,
        trade_volume_24h_btc_normalized: 50522.147736741616
    },
    {
        id: "bitget",
        name: "Bitget",
        year_established: 2018,
        country: "Seychelles",
        description: "",
        url: "https://www.bitget.com/",
        image: "https://assets.coingecko.com/markets/images/540/small/2023-07-25_21.47.43.jpg?1706864507",
        has_trading_incentive: false,
        trust_score: 9,
        trust_score_rank: 10,
        trade_volume_24h_btc: 43457.61921520395,
        trade_volume_24h_btc_normalized: 41685.330560930204
    },
    {
        id: "gate",
        name: "Gate.io",
        year_established: null,
        country: "Cayman Islands",
        description:
            "Gate was established in 2013, and it is the top 10 exchanges in the world in terms of authentic trading volume. It is also the first choice of over 8 million registered customers, covering 130+ countries worldwide, as we are providing the most comprehensive digital asset solutions.",
        url: "https://www.gate.io/",
        image: "https://assets.coingecko.com/markets/images/60/small/gate_io_logo1.jpg?1706864280",
        has_trading_incentive: false,
        trust_score: 9,
        trust_score_rank: 11,
        trade_volume_24h_btc: 46879.61563224771,
        trade_volume_24h_btc_normalized: 32624.413605525908
    },
    {
        id: "bitstamp",
        name: "Bitstamp",
        year_established: 2011,
        country: "Luxembourg",
        description: "",
        url: "https://links.bitstamp.net/c/2223866/1100037/14006",
        image: "https://assets.coingecko.com/markets/images/9/small/bitstamp.jpg?1706864251",
        has_trading_incentive: false,
        trust_score: 9,
        trust_score_rank: 12,
        trade_volume_24h_btc: 4896.560958302859,
        trade_volume_24h_btc_normalized: 2878.368433078903
    },
    {
        id: "bitunix",
        name: "Bitunix",
        year_established: 2021,
        country: "Seychelles",
        description: "",
        url: "https://www.bitunix.com/",
        image: "https://assets.coingecko.com/markets/images/1185/small/APP_icon_1024.png?1706865197",
        has_trading_incentive: false,
        trust_score: 9,
        trust_score_rank: 13,
        trade_volume_24h_btc: 2660.166458732532,
        trade_volume_24h_btc_normalized: 2660.166458732532
    },
    {
        id: "bitfinex",
        name: "Bitfinex",
        year_established: 2012,
        country: "British Virgin Islands",
        description: "",
        url: "https://www.bitfinex.com",
        image: "https://assets.coingecko.com/markets/images/4/small/BItfinex.png?1706864245",
        has_trading_incentive: false,
        trust_score: 9,
        trust_score_rank: 14,
        trade_volume_24h_btc: 4672.9599904009165,
        trade_volume_24h_btc_normalized: 2431.4334783907516
    },
    {
        id: "backpack_exchange",
        name: "Backpack Exchange ",
        year_established: 2023,
        country: "British Virgin Islands",
        description: "A next-gen cryptocurrency exchange. ",
        url: "https://backpack.exchange/",
        image: "https://assets.coingecko.com/markets/images/1387/small/backpack.jpeg?1708663541",
        has_trading_incentive: false,
        trust_score: 9,
        trust_score_rank: 15,
        trade_volume_24h_btc: 1488.5727848457427,
        trade_volume_24h_btc_normalized: 1488.5727848457427
    },
    {
        id: "gemini",
        name: "Gemini",
        year_established: 2014,
        country: "United States",
        description: "",
        url: "https://www.gemini.com/exchange",
        image: "https://assets.coingecko.com/markets/images/50/small/gemini.png?1706864273",
        has_trading_incentive: false,
        trust_score: 9,
        trust_score_rank: 16,
        trade_volume_24h_btc: 1297.929557556553,
        trade_volume_24h_btc_normalized: 1297.929557556553
    },
    {
        id: "hashkey_exchange",
        name: "HashKey Exchange",
        year_established: 2018,
        country: "Hong Kong",
        description:
            "On a mission to set the bar for virtual asset exchanges in compliance, safety, and security, Hash Blockchain Limited (HashKey Exchange) is Hong Kong's first licensed virtual asset exchange for retail users. HashKey Exchange has recently received approval from the Securities and Futures Commission (SFC) of Hong Kong to operate a virtual asset trading platform under Type 1 (Dealing in securities) licence and Type 7 (Providing automated trading services) licence. As HashKey Group's exchange business, HashKey Exchange provides all-in-one trading services for both professional investors (PI) and retail investors. HashKey Exchange has obtained ISO 27001 (Information Security) and ISO 27701 (Data Privacy) management system certifications.",
        url: "https://www.hashkey.com/",
        image: "https://assets.coingecko.com/markets/images/1206/small/hashkey_2.png?1706869603",
        has_trading_incentive: false,
        trust_score: 9,
        trust_score_rank: 17,
        trade_volume_24h_btc: 1206.4124770288904,
        trade_volume_24h_btc_normalized: 1206.4124770288904
    },
    {
        id: "wootrade",
        name: "WOO X",
        year_established: 2019,
        country: "Seychelles",
        description:
            "WOO Network is a deep liquidity network connecting traders, exchanges, institutions, and DeFi platforms with democratized access to the best-in-class liquidity and trading execution at lower or zero cost. Its flagship, WOO X, is a professional trading platform featuring customizable modules and lower to zero fees complete with deep liquidity. WOO Network was founded by Kronos Research, a quantitative trading firm generating $5-10B in daily volume.",
        url: "https://woo.org/",
        image: "https://assets.coingecko.com/markets/images/683/small/woo.png?1706864629",
        has_trading_incentive: false,
        trust_score: 9,
        trust_score_rank: 18,
        trade_volume_24h_btc: 565.686266429364,
        trade_volume_24h_btc_normalized: 565.686266429364
    },
    {
        id: "coinspro",
        name: "Coins.ph",
        year_established: null,
        country: "Philippines",
        description: "",
        url: "https://coins.ph/about",
        image: "https://assets.coingecko.com/markets/images/999/small/coinspro.png?1706864987",
        has_trading_incentive: false,
        trust_score: 9,
        trust_score_rank: 19,
        trade_volume_24h_btc: 158.12932583817053,
        trade_volume_24h_btc_normalized: 158.12932583817053
    },
    {
        id: "lbank",
        name: "LBank",
        year_established: 2015,
        country: "British Virgin Islands",
        description:
            "LBank is a globally based centralized exchange (CEX) platform established in 2015. The platform allows users to buy and sell major crypto assets like Bitcoin (BTC) and Ethereum (ETH) in over 149 fiat currencies, with over 20 payment methods. The company has licenses from the National Futures Association, Italian Organismo degli Agenti e dei Mediatori, and money services businesses in the United States & Canada. The LBank exchange has over 9 million users and accepts clients from over 200 regions.\r\nLBank Exchange provides its users with crypto trading, specialized financial derivatives, and professional asset management services.\r\n ",
        url: "https://www.lbank.com",
        image: "https://assets.coingecko.com/markets/images/118/small/LBank_logo.png?1706864296",
        has_trading_incentive: false,
        trust_score: 8,
        trust_score_rank: 20,
        trade_volume_24h_btc: 24810.951014051185,
        trade_volume_24h_btc_normalized: 24810.951014051185
    },
    {
        id: "whitebit",
        name: "WhiteBIT",
        year_established: 2018,
        country: "Lithuania",
        description: "",
        url: "https://whitebit.com",
        image: "https://assets.coingecko.com/markets/images/418/small/800_800.jpg?1706864419",
        has_trading_incentive: false,
        trust_score: 8,
        trust_score_rank: 21,
        trade_volume_24h_btc: 23834.475024592917,
        trade_volume_24h_btc_normalized: 23834.475024592917
    },
    {
        id: "upbit",
        name: "Upbit",
        year_established: 2017,
        country: "South Korea",
        description: "",
        url: "https://upbit.com",
        image: "https://assets.coingecko.com/markets/images/117/small/upbit.png?1706864294",
        has_trading_incentive: false,
        trust_score: 8,
        trust_score_rank: 22,
        trade_volume_24h_btc: 44257.90621084443,
        trade_volume_24h_btc_normalized: 22815.529816335922
    },
    {
        id: "mxc",
        name: "MEXC",
        year_established: 2018,
        country: "Seychelles",
        description:
            "Established in April 2018, MEXC is one of the world’s leading digital-asset trading platforms. The core team comes from world-class enterprises and financial companies with rich experience in blockchain and financial industries.",
        url: "https://www.mexc.com/",
        image: "https://assets.coingecko.com/markets/images/409/small/MEXC_logo_square.jpeg?1706864416",
        has_trading_incentive: false,
        trust_score: 8,
        trust_score_rank: 23,
        trade_volume_24h_btc: 21398.19083292291,
        trade_volume_24h_btc_normalized: 21398.19083292291
    },
    {
        id: "bitmart",
        name: "BitMart",
        year_established: 2017,
        country: "Cayman Islands",
        description: "",
        url: "https://www.bitmart.com/en",
        image: "https://assets.coingecko.com/markets/images/239/small/Bitmart.png?1706864341",
        has_trading_incentive: false,
        trust_score: 8,
        trust_score_rank: 24,
        trade_volume_24h_btc: 22743.59192773955,
        trade_volume_24h_btc_normalized: 20969.824331948155
    },
    {
        id: "bingx",
        name: "BingX",
        year_established: 2018,
        country: "British Virgin Islands",
        description:
            "Founded in 2018, BingX is a global digital asset, spot, and derivatives trading platform that provides a user-centric and open ecosystem with intuitive social trading features.\r\nCreated to enrich the entire cryptocurrency industry, BingX is a safe, reliable, and user-friendly venue for users to trade their favorite assets.",
        url: "https://bingx.com/",
        image: "https://assets.coingecko.com/markets/images/812/small/YtFwQwJr_400x400.jpg?1706864837",
        has_trading_incentive: false,
        trust_score: 8,
        trust_score_rank: 25,
        trade_volume_24h_btc: 17664.64160945671,
        trade_volume_24h_btc_normalized: 17664.64160945671
    },
    {
        id: "bitvenus_spot",
        name: "BitVenus",
        year_established: 2018,
        country: "British Virgin Islands",
        description:
            "Founded in May 2018, our exchange offers reliable and efficient 24x7 spot and derivatives trading services. Our commitment to continual innovation has allowed us to launch state-of-the-art features, such as a copy trading function, which facilitates both novice and seasoned traders. This persistent focus on enhancement, fueled by a team of seasoned industry professionals, ensures that our product offerings remain top-tier, competitive, and user-friendly. We highly prioritize customer service, boasting a dedicated team ready to provide high-quality support whenever needed. Our dedicated compliance team works meticulously to ensure our trading environment is secure, adhering strictly to all regulatory requirements. All these efforts come together to create a trading platform that offers security, support, and innovative features that make trading both easy and rewarding.",
        url: "https://www.bitvenus.com/",
        image: "https://assets.coingecko.com/markets/images/1253/small/BitVenus_logo.png?1709559502",
        has_trading_incentive: false,
        trust_score: 8,
        trust_score_rank: 26,
        trade_volume_24h_btc: 18250.51640218123,
        trade_volume_24h_btc_normalized: 14224.175764214076
    },
    {
        id: "latoken",
        name: "LATOKEN",
        year_established: 2017,
        country: "Cayman Islands",
        description: "",
        url: "https://latoken.com/",
        image: "https://assets.coingecko.com/markets/images/124/small/latoken.png?1706864301",
        has_trading_incentive: false,
        trust_score: 8,
        trust_score_rank: 27,
        trade_volume_24h_btc: 12160.801245629742,
        trade_volume_24h_btc_normalized: 12160.801245629742
    },
    {
        id: "xt",
        name: "XT.COM",
        year_established: 2018,
        country: "Seychelles",
        description:
            "By consistently expanding its ecosystem, XT.COM is dedicated to providing users with the most secure, trusted, and hassle-free digital asset trading services. Our exchange is built from a desire to give everyone access to digital assets regardless where you are. \r\n\r\nFounded in 2018, XT.COM now serves more than 6 million registered users, over 500,000+ monthly active users and 40+ million users in the ecosystem. Covering a rich variety of  trading categories together with a NFT aggregated marketplace,  our platform strives to cater to its large user base by providing a secure, trusted and intuitive trading experience.\r\n\r\nAs the world’s first social-infused digital assets trading platform, XT.COM also supports social networking platform based transactions to make our crypto services more accessible to users all over the world. Furthermore, to ensure optimal data integrity and security, we see user security as our top priority at XT.COM. ",
        url: "https://www.xt.com/",
        image: "https://assets.coingecko.com/markets/images/404/small/logo400x400.png?1706864415",
        has_trading_incentive: false,
        trust_score: 8,
        trust_score_rank: 28,
        trade_volume_24h_btc: 11155.222847711277,
        trade_volume_24h_btc_normalized: 11155.222847711277
    },
    {
        id: "biconomy",
        name: "Biconomy",
        year_established: 2019,
        country: "Canada",
        description:
            "Biсonomy is a Canadian cryptocurrency exchange founded on October 1, 2019.\r\nThe exchange has a Canadian trading license and has also recently received a US MSB license.\r\nBiconomy only hosts high-quality projects and coins. It is also possible to buy a cryptocurrency for fiat using the AdvCash solution.",
        url: "https://www.biconomy.com/",
        image: "https://assets.coingecko.com/markets/images/633/small/biconomy-cex.png?1706864578",
        has_trading_incentive: false,
        trust_score: 8,
        trust_score_rank: 29,
        trade_volume_24h_btc: 10117.031892700035,
        trade_volume_24h_btc_normalized: 10117.031892700035
    },
    {
        id: "coinw",
        name: "CoinW",
        year_established: 2017,
        country: "United Arab Emirates",
        description:
            "What Is CoinW?\r\nCoinW stands as a pinnacle in the world of crypto trading platforms, where our unwavering commitment to security, transparency, and user-centric principles sets us apart. Powered by cutting-edge technology, boasting deep liquidity, and offering support for a diverse array of cryptocurrencies, we have cultivated a vast and dedicated user base, solidifying our position as one of the most secure exchanges globally.\r\n\r\nDedicated to upholding the highest regulatory standards, we prioritize security, transparency, and compliance to contribute actively to the advancement of the crypto industry. At CoinW, we take pride in serving over 10 million users worldwide, earning our reputation as a beacon of security and reliability in the dynamic realm of cryptocurrency. Join us on this journey, where your assets are safeguarded, and your trading experience is elevated to new heights.\r\n\r\nWho Are the Founders of CoinW?\r\nIncepted in 2017 by a fusion of crypto, cybersecurity, and finance virtuosos, CoinW has established 16 Localized Trading Service Centers spanning 13 distinct countries. With a robust workforce comprising over 1,000 talents representing 30 diverse nations, CoinW stands as the quintessential embodiment of a global and professional entity.\r\n\r\nWhen Did CoinW Launch?\r\nCoinW was launched in 2017.\r\n\r\nWhere Is CoinW Located?\r\nBased in the vibrant city of Dubai, UAE, CoinW has expanded its global presence with 16 Localized Trading Service Centers spanning 13 countries. Our reach extends to key locations such as Dubai, Singapore, Turkey, South Korea, Japan, the Philippines, Malaysia, Australia, Vietnam, India, Nigeria, Canada, and Russia. Serving customers in over 200 regions and countries, CoinW is dedicated to providing a seamless and localized trading experience.\r\n\r\nAs a forward-thinking crypto trading platform, we prioritize collaboration with international regulatory bodies and organizations, contributing to the establishment of a safe and secure environment for our users.\r\n\r\nWhat Coins Are Supported on CoinW?\r\nCoinW boasts a vast array of over 1,000 listed crypto tokens, offering more than 500 spot trading pairs. Popular coins include BTC, ETH, BGB, XRP, PEPE, DOGE, SHIB, BNB, LTC, APT and more.\r\n\r\nHow Much Are CoinW Fees?\r\nWhen users conduct currency transactions on CoinW, the platform will charge users a certain fee to support the operation of the platform.User fees for makers and takers on the platform will be charged according to different rules. Currently, the basic fees for maker and takers on the platform are both 0.2%.\r\n\r\nIs It Possible To Use Leverage or Margin Trading on CoinW?\r\nCoinW empowers traders seeking strategic leverage through our comprehensive options for both spot and Futures trading. Our platform offers unparalleled flexibility, allowing users to utilize leverage ratios of up to 200x in Futures and 6x in ETF trading. This means that traders can amplify their positions, opening the door to potential profit maximization in crypto market.\r\n",
        url: "https://www.coinw.com/",
        image: "https://assets.coingecko.com/markets/images/1172/small/coinw.jpeg?1706865186",
        has_trading_incentive: false,
        trust_score: 8,
        trust_score_rank: 30,
        trade_volume_24h_btc: 8433.232223820043,
        trade_volume_24h_btc_normalized: 8433.232223820043
    },
    {
        id: "fastex",
        name: "Fastex",
        year_established: null,
        country: "Lithuania",
        description: "",
        url: "https://exchange.fastex.com/",
        image: "https://assets.coingecko.com/markets/images/1091/small/fastex.png?1706865112",
        has_trading_incentive: false,
        trust_score: 8,
        trust_score_rank: 31,
        trade_volume_24h_btc: 6471.826435147846,
        trade_volume_24h_btc_normalized: 6471.826435147846
    },
    {
        id: "azbit",
        name: "Azbit",
        year_established: null,
        country: "Seychelles",
        description:
            "Azbit is a new generation exchange offering the most in-demand services on the market. Spot exchange, margin trading, crypto-backed loans.",
        url: "https://azbit.com/",
        image: "https://assets.coingecko.com/markets/images/787/small/logo.png?1706864819",
        has_trading_incentive: false,
        trust_score: 8,
        trust_score_rank: 32,
        trade_volume_24h_btc: 3144.7314730624207,
        trade_volume_24h_btc_normalized: 3144.7314730624207
    },
    {
        id: "pointpay",
        name: "PointPay",
        year_established: 2018,
        country: "Saint Vincent and the Grenadines",
        description: "",
        url: "https://exchange.pointpay.io/",
        image: "https://assets.coingecko.com/markets/images/1060/small/pointpay.png?1706865085",
        has_trading_incentive: false,
        trust_score: 8,
        trust_score_rank: 33,
        trade_volume_24h_btc: 2640.5893005502985,
        trade_volume_24h_btc_normalized: 2640.5893005502985
    },
    {
        id: "bitmax",
        name: "AscendEX (BitMax)",
        year_established: 2018,
        country: "Singapore",
        description:
            "AscendEX (formerly BitMax) is a leading global digital asset financial platform founded by a group of Wall Street quantitative trading veterans in 2018, building on core value of “Efficiency, Resilience and Transparency.” \r\n \r\nDriven by its continuous innovative product development and early-mover advantage in strategic alignment with the leading projects from DeFi ecosystem, AscendEX offers trading services across over 200 trading pairs across cash, margin, and futures products, in particular margin trading of over 50 tokens in cross-asset collateral mode and futures trading in both cross-asset and isolated margin modes.",
        url: "https://ascendex.com/en/global-digital-asset-platform",
        image: "https://assets.coingecko.com/markets/images/277/small/%E5%8E%9F%E8%89%B2.png?1706864357",
        has_trading_incentive: false,
        trust_score: 8,
        trust_score_rank: 34,
        trade_volume_24h_btc: 3280.795421191754,
        trade_volume_24h_btc_normalized: 2440.088739639459
    },
    {
        id: "phemex",
        name: "Phemex",
        year_established: 2019,
        country: "Singapore",
        description:
            "Launched in 2019, Phemex is a Singapore-based cryptocurrency and derivatives trading platform led by former Morgan Stanley executives. Serving around 5 million active users in over 200 countries, Phemex supports 150+ trading pairs with up to 100x leverage.\r\n\r\n-  Fee Structure: 0.1% for both maker and taker\r\n-  Contract Fee Structure: 0.01% for maker and 0.06% for taker\r\n-  Up to $100 Welcome Bonus for new users\r\n-  Earn up to 8.5% APY interest income on crypto assets\r\n-  Free academy with 450+ carefully curated articles about crypto & trading\r\n-  Security: Hierarchical Deterministic Cold Wallet System with 2-level human scrutiny offline signatures.",
        url: "https://phemex.com/",
        image: "https://assets.coingecko.com/markets/images/564/small/phemex_logo.png?1706864519",
        has_trading_incentive: false,
        trust_score: 8,
        trust_score_rank: 35,
        trade_volume_24h_btc: 2179.207319210133,
        trade_volume_24h_btc_normalized: 2179.207319210133
    },
    {
        id: "btse",
        name: "BTSE",
        year_established: 2018,
        country: "British Virgin Islands",
        description:
            "BTSE is a leading digital asset exchange that empowers users by offering a simple and secure way to trade. Its growing suite of financial services is designed to bridge traditional finance with digital assets solutions. BTSE's innovative technology offers a set of digital financial solutions featuring multi-currency spot and derivatives trading, in addition to NFT and exchange white labels, over-the-counter (OTC) trading, asset management, and payment gateways. Additionally, BTSE provides an all-in-one order book, strict security protocols, an insurance fund, cold storage for more than 99% of assets and no withdrawal limits on over 12 fiat currencies and 100 cryptocurrencies.",
        url: "https://www.btse.com/",
        image: "https://assets.coingecko.com/markets/images/464/small/BTSE.jpg?1706864449",
        has_trading_incentive: false,
        trust_score: 8,
        trust_score_rank: 36,
        trade_volume_24h_btc: 1093.699399502139,
        trade_volume_24h_btc_normalized: 1093.699399502139
    },
    {
        id: "coinex",
        name: "CoinEx",
        year_established: 2017,
        country: "Samoa",
        description: "",
        url: "https://www.coinex.com/",
        image: "https://assets.coingecko.com/markets/images/135/small/coinex.jpg?1706864305",
        has_trading_incentive: false,
        trust_score: 8,
        trust_score_rank: 37,
        trade_volume_24h_btc: 1059.4251066153656,
        trade_volume_24h_btc_normalized: 1059.4251066153656
    },
    {
        id: "exmo",
        name: "EXMO",
        year_established: 2013,
        country: "United Kingdom",
        description: "",
        url: "https://exmo.com/",
        image: "https://assets.coingecko.com/markets/images/59/small/tt_ava.jpg?1706864278",
        has_trading_incentive: false,
        trust_score: 8,
        trust_score_rank: 38,
        trade_volume_24h_btc: 953.6893260180294,
        trade_volume_24h_btc_normalized: 953.6893260180294
    },
    {
        id: "bitbank",
        name: "Bitbank",
        year_established: 2016,
        country: "Japan",
        description: "",
        url: "https://bitbank.cc/",
        image: "https://assets.coingecko.com/markets/images/122/small/bitbank.jpg?1706864298",
        has_trading_incentive: false,
        trust_score: 8,
        trust_score_rank: 39,
        trade_volume_24h_btc: 823.4244122797335,
        trade_volume_24h_btc_normalized: 823.4244122797335
    },
    {
        id: "max_maicoin",
        name: "Max Maicoin",
        year_established: null,
        country: "Taiwan",
        description: "",
        url: "https://max.maicoin.com",
        image: "https://assets.coingecko.com/markets/images/218/small/max.jpg?1706864331",
        has_trading_incentive: false,
        trust_score: 8,
        trust_score_rank: 40,
        trade_volume_24h_btc: 457.8103897154399,
        trade_volume_24h_btc_normalized: 457.8103897154399
    },
    {
        id: "bitopro",
        name: "BitoPro",
        year_established: 2018,
        country: "Taiwan",
        description: "",
        url: "https://www.bitopro.com/",
        image: "https://assets.coingecko.com/markets/images/358/small/bitopro_coingecko_250x250_%281%29.png?1706864386",
        has_trading_incentive: false,
        trust_score: 8,
        trust_score_rank: 41,
        trade_volume_24h_btc: 375.0498243590762,
        trade_volume_24h_btc_normalized: 375.0498243590762
    },
    {
        id: "indodax",
        name: "Indodax",
        year_established: 2014,
        country: "Indonesia",
        description: "",
        url: "https://indodax.com",
        image: "https://assets.coingecko.com/markets/images/3/small/logogram-Indodax-new-_JPG_format.jpg?1706864243",
        has_trading_incentive: false,
        trust_score: 8,
        trust_score_rank: 42,
        trade_volume_24h_btc: 289.09261714198357,
        trade_volume_24h_btc_normalized: 289.09261714198357
    },
    {
        id: "luno",
        name: "Luno",
        year_established: 2013,
        country: "Singapore",
        description: "",
        url: "https://www.luno.com",
        image: "https://assets.coingecko.com/markets/images/33/small/RGB_LUNO_SYMBOL_NAVY_BLUE_1.png?1706864266",
        has_trading_incentive: false,
        trust_score: 8,
        trust_score_rank: 43,
        trade_volume_24h_btc: 194.44513052584892,
        trade_volume_24h_btc_normalized: 194.44513052584892
    },
    {
        id: "digifinex",
        name: "DigiFinex",
        year_established: 2018,
        country: "Seychelles",
        description: "",
        url: "https://www.digifinex.com/",
        image: "https://assets.coingecko.com/markets/images/225/small/DF_logo.png?1706864334",
        has_trading_incentive: false,
        trust_score: 7,
        trust_score_rank: 44,
        trade_volume_24h_btc: 26337.781684951893,
        trade_volume_24h_btc_normalized: 26337.781684951893
    },
    {
        id: "hotcoin_global",
        name: "Hotcoin Global",
        year_established: 2017,
        country: "Seychelles",
        description:
            "Operating out of Australia, Hotcoin Global is a digital asset trading platform. The obtained two different licenses to conduct its operations from AUSTRAC: digital currency trading and foreign currencies exchange. As of 2022, the centralized cryptocurrency exchange (CEX) had an estimated 5 million active users, with its daily transaction volume reaching billions of dollars.",
        url: "https://www.hotcoin.com",
        image: "https://assets.coingecko.com/markets/images/1345/small/Hotcoin_logo.jpg?1706901913",
        has_trading_incentive: false,
        trust_score: 7,
        trust_score_rank: 45,
        trade_volume_24h_btc: 37927.6227325596,
        trade_volume_24h_btc_normalized: 19294.390717459595
    },
    {
        id: "p2pb2b",
        name: "P2B",
        year_established: 2018,
        country: "Lithuania",
        description:
            "P2B is a top crypto platform in Europe and has gotten into the TOP-3 Crypto Exchanges by growth speed. It offers the best go-to-market experience to diverse crypto startups. At the exchange, investors can find a wide variety of newly-launched tokens.\r\n\r\n\r\nThe platform attracts new crypto projects due to the high-level liquidity of the crypto exchange. One of the essential benefits of the crypto exchange is the high-level security of every launch and operation. It's in the TOP-15 in Cer.Live security rate. \r\n\r\n\r\nThe exchange has 6-year-old experience in the crypto field and has presented more than 2,000 crypto projectsʼ launches. The go-to-market team of the exchange has designed a well-thought strategy for marketing and promoting newly-launched projects to enhance their liquidity and involve new investors.\r\n\r\n\r\nP2B offers a top-grade launchpad with extended functionality for newly-launched crypto projects. The platform offers additional liquidity services to support a token price after a listing stage and avoid a price drop. It doesn't have limitations, a ticket system, and doesn't hold tokens. The total amount of funds raised through launchpads is already more than $10 million, and the top results from one launchpad are $2+ million.\r\n\r\n\r\nP2B is popular among newly-launched crypto projects due to easy-to-go onboarding, a loyal listing requirement for the 1st listing, expertise, and well-designed tools for the project's promotion. The exchange also contributes to the development of WEB 3.0 by creating the Fund of Rising Stars to support projects with high potential and strong ideas.\r\n\r\n\r\nJoin the prosperous P2B community—the #1 place to be in crypto.\r\n\r\nGet your exciting trading experience and earn fast and securely with 24/7 support.\r\n\r\n",
        url: "https://p2pb2b.com/",
        image: "https://assets.coingecko.com/markets/images/251/small/ow0xng56_400x400.jpeg?1706864347",
        has_trading_incentive: false,
        trust_score: 7,
        trust_score_rank: 46,
        trade_volume_24h_btc: 26038.713154101144,
        trade_volume_24h_btc_normalized: 13744.38352287771
    },
    {
        id: "deepcoin",
        name: "Deepcoin",
        year_established: 2018,
        country: "Seychelles",
        description:
            "Deepcoin Exchange offers groundbreaking tools for you to buy and sell over 120 cryptocurrencies. Since 2018, we have provided a secure and reliable way for you to invest in spot and futures trading to our over 1 million users.",
        url: "https://www.deepcoin.com/",
        image: "https://assets.coingecko.com/markets/images/1005/small/deepcoin.jpeg?1706864992",
        has_trading_incentive: false,
        trust_score: 7,
        trust_score_rank: 47,
        trade_volume_24h_btc: 16549.11037498013,
        trade_volume_24h_btc_normalized: 11888.569089472972
    },
    {
        id: "bigone",
        name: "BigONE",
        year_established: 2017,
        country: "Seychelles",
        description: "",
        url: "https://bigone.com",
        image: "https://assets.coingecko.com/markets/images/100/small/qcFFufEY_400x400.jpg?1706864287",
        has_trading_incentive: false,
        trust_score: 7,
        trust_score_rank: 48,
        trade_volume_24h_btc: 10444.199127764821,
        trade_volume_24h_btc_normalized: 10444.199127764821
    },
    {
        id: "bithumb",
        name: "Bithumb",
        year_established: 2014,
        country: "South Korea",
        description: "",
        url: "https://www.bithumb.com/",
        image: "https://assets.coingecko.com/markets/images/6/small/bithumb_BI.png?1706864248",
        has_trading_incentive: false,
        trust_score: 7,
        trust_score_rank: 49,
        trade_volume_24h_btc: 8963.556383905341,
        trade_volume_24h_btc_normalized: 8963.556383905341
    },
    {
        id: "cointr",
        name: "CoinTR Pro",
        year_established: 2022,
        country: "Lithuania",
        description: "",
        url: "https://www.cointr.pro/",
        image: "https://assets.coingecko.com/markets/images/1028/small/cointr.png?1706865058",
        has_trading_incentive: false,
        trust_score: 7,
        trust_score_rank: 50,
        trade_volume_24h_btc: 8853.337801045525,
        trade_volume_24h_btc_normalized: 8853.337801045525
    },
    {
        id: "toobit",
        name: "Toobit",
        year_established: 2022,
        country: "Cayman Islands",
        description: "",
        url: "https://www.toobit.com/",
        image: "https://assets.coingecko.com/markets/images/1139/small/Toobit_logo400X400.png?1706865157",
        has_trading_incentive: false,
        trust_score: 7,
        trust_score_rank: 51,
        trade_volume_24h_btc: 8962.442296805742,
        trade_volume_24h_btc_normalized: 8274.557024065702
    },
    {
        id: "tapbit",
        name: "Tapbit",
        year_established: 2019,
        country: "United States",
        description:
            "Tapbit offers secure and stable trading services for global investors in mainstream crypto assets such as BTC, ETH, SOL, and USDC. The platform holds the MSB fiat currency business license issued by the U.S. federal government, the MSB fiat currency business license issued by the Canadian government, the NFA general financial license, and the crypto and forex business license issued by SVGFSA. Additionally, we safeguard all your assets on Tapbit through a multi-million-dollar insurance fund Tapbit provides users with cutting-edge technology, featuring a core aggregation engine that stands as one of the most advanced technological products in the current market. With fault tolerance and exceptional processing speed, it can address concurrent issues arising from instantaneous high volumes of transactions and settlements. Our security measures include banking-grade SSL encryption, multi-signature capabilities, and hot & cold wallet separation technology, all working together to rigorously protect the security of all user assets  Tapbit stands out as one of the safest and most reliable cryptocurrency service platforms in the current market. Global investors can utilize and benefit from the platform without worrying about potential risks associated with the field, thanks to the application of advanced technology and innovative algorithms.",
        url: "https://www.tapbit.com/",
        image: "https://assets.coingecko.com/markets/images/1374/small/Tapbit-Logo.png?1706865388",
        has_trading_incentive: false,
        trust_score: 7,
        trust_score_rank: 52,
        trade_volume_24h_btc: 7098.233771768349,
        trade_volume_24h_btc_normalized: 7098.233771768349
    },
    {
        id: "pionex",
        name: "Pionex",
        year_established: 2019,
        country: "British Virgin Islands",
        description: "",
        url: "https://www.pionex.com",
        image: "https://assets.coingecko.com/markets/images/1026/small/pionex.png?1706865056",
        has_trading_incentive: false,
        trust_score: 7,
        trust_score_rank: 53,
        trade_volume_24h_btc: 8950.0947355699,
        trade_volume_24h_btc_normalized: 5688.735469004927
    },
    {
        id: "bitvavo",
        name: "Bitvavo",
        year_established: 2018,
        country: "Netherlands",
        description: "",
        url: "https://bitvavo.com/en",
        image: "https://assets.coingecko.com/markets/images/714/small/bitvavo-mark-square-black.png?1706864670",
        has_trading_incentive: false,
        trust_score: 7,
        trust_score_rank: 54,
        trade_volume_24h_btc: 4208.284769867283,
        trade_volume_24h_btc_normalized: 4208.284769867283
    },
    {
        id: "probit",
        name: "ProBit Global",
        year_established: 2017,
        country: "Seychelles",
        description: "",
        url: "https://www.probit.com/",
        image: "https://assets.coingecko.com/markets/images/370/small/probit.png?1706864390",
        has_trading_incentive: false,
        trust_score: 6,
        trust_score_rank: 55,
        trade_volume_24h_btc: 10386.505666214622,
        trade_volume_24h_btc_normalized: 3788.082117712427
    },
    {
        id: "bitflyer",
        name: "bitFlyer",
        year_established: 2014,
        country: "Japan",
        description: "",
        url: "https://bitflyer.com/en-eu/",
        image: "https://assets.coingecko.com/markets/images/5/small/bitFlyer-logo.png?1706864247",
        has_trading_incentive: false,
        trust_score: 7,
        trust_score_rank: 56,
        trade_volume_24h_btc: 2332.1527446016275,
        trade_volume_24h_btc_normalized: 2332.1527446016275
    },
    {
        id: "bitdelta",
        name: "BitDelta",
        year_established: 2023,
        country: "Vanuatu",
        description:
            "BitDelta is a global trading platform servicing in 120+ countries with a mission to revolutionize the financial landscape by empowering young individuals and ambitious investors to ignite their trading journey. The platform offers a comprehensive trading experience through a range of innovative features, like Spot Trading, Card Crypto Purchases, Token Launchpad Services and more. Along with these features, BitDelta users are able to diversify their portfolios into a variety of assets, all while using a highly secure asset custodian. With a steadfast commitment to making trading accessible for all, BitDelta aims to create a sophisticated and engaging trading experience where every trade counts.",
        url: "https://bitdelta.com/",
        image: "https://assets.coingecko.com/markets/images/1317/small/BitDelta_Logo_200x200.png?1706865321",
        has_trading_incentive: false,
        trust_score: 7,
        trust_score_rank: 57,
        trade_volume_24h_btc: 2150.9112945460733,
        trade_volume_24h_btc_normalized: 2150.9112945460733
    },
    {
        id: "bydfi",
        name: "BYDFi",
        year_established: 2020,
        country: null,
        description: "",
        url: "https://www.bydfi.com/en",
        image: "https://assets.coingecko.com/markets/images/1186/small/photo_2024-03-20_11-10-03.jpg?1710914231",
        has_trading_incentive: false,
        trust_score: 7,
        trust_score_rank: 58,
        trade_volume_24h_btc: 1830.650079558935,
        trade_volume_24h_btc_normalized: 1830.650079558935
    },
    {
        id: "btcturk",
        name: "BtcTurk | Kripto",
        year_established: 2013,
        country: "Turkey",
        description: "",
        url: "https://kripto.btcturk.com/en",
        image: "https://assets.coingecko.com/markets/images/223/small/btctrurk_kripto.png?1706864333",
        has_trading_incentive: false,
        trust_score: 7,
        trust_score_rank: 59,
        trade_volume_24h_btc: 2808.8635358332363,
        trade_volume_24h_btc_normalized: 1791.4429041286216
    },
    {
        id: "paribu",
        name: "Paribu",
        year_established: null,
        country: "Turkey",
        description: null,
        url: "https://www.paribu.com/",
        image: "https://assets.coingecko.com/markets/images/136/small/paribu.jpg?1706864307",
        has_trading_incentive: null,
        trust_score: 7,
        trust_score_rank: 60,
        trade_volume_24h_btc: 1955.5126928225468,
        trade_volume_24h_btc_normalized: 1713.0456802269607
    },
    {
        id: "cryptology",
        name: "Cryptology",
        year_established: 2018,
        country: "Lithuania",
        description: "",
        url: "https://cryptology.com/",
        image: "https://assets.coingecko.com/markets/images/287/small/logo-symbol.png?1706864361",
        has_trading_incentive: false,
        trust_score: 7,
        trust_score_rank: 61,
        trade_volume_24h_btc: 1090.4375511832754,
        trade_volume_24h_btc_normalized: 1090.4375511832754
    },
    {
        id: "dextrade",
        name: "Dex-Trade",
        year_established: 2019,
        country: "Belize",
        description:
            "Dex-Trade is a centralized cryptocurrency exchange founded in 2017 and registered in Belize. This is a modern space for safe and comfortable trading with minimal commissions.\r\n\r\nDex-Trade is a universal exchange for both beginners and professional traders. The minimum spread and high liquidity in order books allow you to trade efficiently with orders of any volume.\r\nAlong with global opportunities, the exchange also provides a demo trading mode for risk-free testing of your trading strategies. Our dedicated support team is online 24/7 to assist you with any questions.\r\n\r\nYou can learn more about Dex-Trade on the website.\r\nhttps://dex-trade.com/info/about\r\n\r\nIf you are looking for listing and promotion options with Dex-Trade please visit our listing page and a personal manager will help you to utilize our proven tools and intelligent market-making system to engage with the vast exchange community in the best possible way. https://dex-trade.com/listing",
        url: "https://dex-trade.com/",
        image: "https://assets.coingecko.com/markets/images/380/small/Dex-Trade.png?1706864395",
        has_trading_incentive: false,
        trust_score: 7,
        trust_score_rank: 62,
        trade_volume_24h_btc: 1001.6989184602099,
        trade_volume_24h_btc_normalized: 1001.6989184602099
    },
    {
        id: "bitkub",
        name: "Bitkub",
        year_established: 2018,
        country: "Thailand",
        description: "",
        url: "https://www.bitkub.com",
        image: "https://assets.coingecko.com/markets/images/249/small/bitkub.png?1706864345",
        has_trading_incentive: false,
        trust_score: 7,
        trust_score_rank: 63,
        trade_volume_24h_btc: 888.6449940565948,
        trade_volume_24h_btc_normalized: 888.6449940565948
    },
    {
        id: "bitso",
        name: "Bitso",
        year_established: 2014,
        country: "Gibraltar",
        description: "",
        url: "https://bitso.com",
        image: "https://assets.coingecko.com/markets/images/8/small/Bitso-icon-dark.png?1706864249",
        has_trading_incentive: false,
        trust_score: 7,
        trust_score_rank: 64,
        trade_volume_24h_btc: 692.3318634126466,
        trade_volume_24h_btc_normalized: 692.3318634126466
    },
    {
        id: "bitcastle",
        name: "bitcastle",
        year_established: 2019,
        country: "Lithuania",
        description:
            "bitcastle is all in one global platform including crypto trading, FX trading and binary option trading first launched in July 2019.  In May 2022, bitcastle renewed it's platform with a brand new user interface, new features and token listings. With offices in Singapore, Vietnam and Japan, bitcastle maximizes the strengths of the diverse team with various experiences to deliver the best financial services for its users.  Notable features of the platform include 0% trading fee for major currency pairs and High & Low binary trading option. bitcastle High & Low option allows users to see return on their investment in as little as 5 seconds, which is the fastest period in the world. bitcastle aims to be a platform that can be enjoyed by both seasoned traders as well as beginners.  CASTLE is bitcastle's native token. CASTLE can be used to reduce transaction fees on the platform by up to 60%. At selected intervals, 20% of bitcastle's profits will be used to buy back CASTLE tokens, and burn them.  The bitcastle apps is now available for both android and IOS, enabling users to access it's platform.",
        url: "https://bitcastle.io/en",
        image: "https://assets.coingecko.com/markets/images/1341/small/bitcastle_logo.png?1706865343",
        has_trading_incentive: false,
        trust_score: 7,
        trust_score_rank: 65,
        trade_volume_24h_btc: 2901.143191141508,
        trade_volume_24h_btc_normalized: 531.2988468667576
    },
    {
        id: "bitazza",
        name: "Bitazza",
        year_established: 2021,
        country: "Thailand",
        description: "Bitazza is ASEAN's locally-based digital asset platform. ",
        url: "https://trade.bitazza.com/gl/exchange/",
        image: "https://assets.coingecko.com/markets/images/837/small/btzlogo200x200_darkgreen.png?1706864859",
        has_trading_incentive: false,
        trust_score: 7,
        trust_score_rank: 66,
        trade_volume_24h_btc: 349.21082601897314,
        trade_volume_24h_btc_normalized: 349.21082601897314
    },
    {
        id: "korbit",
        name: "Korbit",
        year_established: 2013,
        country: "South Korea",
        description: "",
        url: "https://www.korbit.co.kr/",
        image: "https://assets.coingecko.com/markets/images/28/small/korbit-logo.png?1706864263",
        has_trading_incentive: false,
        trust_score: 7,
        trust_score_rank: 67,
        trade_volume_24h_btc: 254.30745914379153,
        trade_volume_24h_btc_normalized: 254.30745914379153
    },
    {
        id: "bitexen",
        name: "Bitexen",
        year_established: 2018,
        country: "Turkey",
        description: "",
        url: "https://www.bitexen.com/",
        image: "https://assets.coingecko.com/markets/images/693/small/Bitexen_Logo_Short.png?1706864642",
        has_trading_incentive: false,
        trust_score: 7,
        trust_score_rank: 68,
        trade_volume_24h_btc: 239.1631209371074,
        trade_volume_24h_btc_normalized: 239.1631209371074
    },
    {
        id: "kanga",
        name: "Kanga",
        year_established: 2018,
        country: "Belize",
        description: "",
        url: "https://kanga.exchange/",
        image: "https://assets.coingecko.com/markets/images/852/small/KaNGa_logo.png?1706864870",
        has_trading_incentive: false,
        trust_score: 7,
        trust_score_rank: 69,
        trade_volume_24h_btc: 222.70854130539678,
        trade_volume_24h_btc_normalized: 222.70854130539678
    },
    {
        id: "itbit",
        name: "itBit",
        year_established: 2013,
        country: "United States",
        description: null,
        url: "https://www.itbit.com/",
        image: "https://assets.coingecko.com/markets/images/26/small/itbit.png?1706864262",
        has_trading_incentive: false,
        trust_score: 7,
        trust_score_rank: 70,
        trade_volume_24h_btc: 129.53773035702838,
        trade_volume_24h_btc_normalized: 129.53773035702838
    },
    {
        id: "nominex",
        name: "Nominex",
        year_established: 2019,
        country: "Seychelles",
        description:
            "New trading platform for convenient trading experience with low fees and numerous instruments. \r\n\r\nAbsolutely unique affiliate program that allows to earn from an infinite number of referral levels, compared to 2-3 levels at all other exchanges. \r\n\r\nA unique model for the free 2 phases distribution of the native NMX token.\r\n\r\nAdvanced Trading Instruments – using Stop, Stop Limit, Trailing Stop, Scaled and other types of orders brings some kind of trading automation without the need to develop a trading bot, which allows to easily get more profit while trading.",
        url: "https://www.nominex.io",
        image: "https://assets.coingecko.com/markets/images/530/small/logo-200x200.png?1706864500",
        has_trading_incentive: false,
        trust_score: 7,
        trust_score_rank: 71,
        trade_volume_24h_btc: 132.90922573292306,
        trade_volume_24h_btc_normalized: 121.25556679952822
    },
    {
        id: "cex",
        name: "CEX.IO",
        year_established: 2013,
        country: "United Kingdom",
        description: "",
        url: "https://trade.cex.io/",
        image: "https://assets.coingecko.com/markets/images/56/small/main-icon.png?1706864277",
        has_trading_incentive: false,
        trust_score: 7,
        trust_score_rank: 72,
        trade_volume_24h_btc: 102.57002904165184,
        trade_volume_24h_btc_normalized: 102.57002904165184
    },
    {
        id: "nonkyc_io",
        name: "Nonkyc.io",
        year_established: 2023,
        country: "Seychelles",
        description:
            "About NonKyc.io Founded in 2023, NonKyc.io strives to provide its users with the best trading experience and give small and medium market cap assets a reliable trading hub. Our goal is to maintain a fast and user friendly system while also concentrating on security to keep users, data, and assets safe. Security of our users' data & assets is always our top priority and we are focused on building an easy to use digital asset trading platform for everyone to enjoy.  The NonKYC platform system is NOT from some predesigned script package or preexisting codebase. It has been created from the ground up by professional developers who are well experienced in Cryptocurrency. NonKYC has been designed to scale horizontally as we grow to become a top tier exchange.",
        url: "https://nonkyc.io",
        image: "https://assets.coingecko.com/markets/images/1281/small/NKYC-Logo.png?1706865279",
        has_trading_incentive: false,
        trust_score: 7,
        trust_score_rank: 73,
        trade_volume_24h_btc: 59.80097454788739,
        trade_volume_24h_btc_normalized: 59.80097454788739
    },
    {
        id: "xeggex",
        name: "XeggeX",
        year_established: 2021,
        country: "Seychelles",
        description:
            "Founded in 2021, XeggeX.com strives to provide its users with the best trading experience and give small and medium market cap assets a reliable trading hub. Our goal is to maintain a fast and user friendly system while also concentrating on security to keep users, data, and assets safe. Security of our users' data & assets is always our top priority and we are focused on building an easy to use digital asset trading platform for everyone to enjoy.",
        url: "https://xeggex.com",
        image: "https://assets.coingecko.com/markets/images/1299/small/XeggeX_Logo_200.png?1706865292",
        has_trading_incentive: false,
        trust_score: 7,
        trust_score_rank: 74,
        trade_volume_24h_btc: 46.08019640706034,
        trade_volume_24h_btc_normalized: 46.08019640706034
    },
    {
        id: "coindcx",
        name: "CoinDCX",
        year_established: 2018,
        country: "Singapore",
        description:
            "Started on April 7th, 2018, CoinDCX is a Singapore-based company that specializes in crypto-enabled financial services. Offering you the simplest yet robust trading environment to trade 200+ coins, 500+ markets, and 150+ coins on leverage at lightning speed.\r\n\r\nWith major fintech innovations going across the world, DCX is bringing a revolution with its crypto-based products. DCX is not just for the banked or unbanked, DCX aims to build an all-inclusive ecosystem by bringing trust between the trustless. DCX is focused on developing borderless financial services which ensure faster, simpler, and uninterrupted flow of capital.\r\nThrough its array of products, DCX is upgrading lives every day.\r\n",
        url: "https://www.coindcx.com",
        image: "https://assets.coingecko.com/markets/images/520/small/coindcx.png?1706864493",
        has_trading_incentive: false,
        trust_score: 7,
        trust_score_rank: 75,
        trade_volume_24h_btc: 40.97097635457372,
        trade_volume_24h_btc_normalized: 40.97097635457372
    },
    {
        id: "kuna",
        name: "Kuna Exchange",
        year_established: null,
        country: "United Kingdom",
        description: "",
        url: "https://kuna.io/",
        image: "https://assets.coingecko.com/markets/images/97/small/kuna_exchange.png?1706864284",
        has_trading_incentive: false,
        trust_score: 7,
        trust_score_rank: 76,
        trade_volume_24h_btc: 32.687619537948024,
        trade_volume_24h_btc_normalized: 32.687619537948024
    },
    {
        id: "stormgain",
        name: "Stormgain",
        year_established: null,
        country: "Saint Vincent and the Grenadines",
        description:
            "StormGain is a crypto trading platform for everyone. It’s a convenient solution for those who want to profit from either the growth or decline of the cryptocurrency market and from long-term investments in crypto assets.\r\nAvailable on any device, StormGain allows you to start trading the most popular and most capitalised coins with a multiplier of up to 200x, or you can just buy and hodl crypto.",
        url: "https://stormgain.com/?utm_id=1DSE&utm_source=coingecko_storm&utm_medium=media&utm_campaign=listing&utm_country=en",
        image: "https://assets.coingecko.com/markets/images/608/small/CpDGk9Hn_400x400.png?1706864555",
        has_trading_incentive: false,
        trust_score: 7,
        trust_score_rank: 77,
        trade_volume_24h_btc: 18.511968739662265,
        trade_volume_24h_btc_normalized: 18.511968739662265
    },
    {
        id: "nice_hash",
        name: "NiceHash",
        year_established: null,
        country: "Slovenia",
        description: "",
        url: "https://www.nicehash.com",
        image: "https://assets.coingecko.com/markets/images/546/small/logo_small_light.png?1706864513",
        has_trading_incentive: false,
        trust_score: 7,
        trust_score_rank: 78,
        trade_volume_24h_btc: 11.803130704065234,
        trade_volume_24h_btc_normalized: 11.803130704065234
    },
    {
        id: "bitmex_spot",
        name: "BitMEX",
        year_established: null,
        country: "Seychelles",
        description: "",
        url: "https://www.bitmex.com/spot/",
        image: "https://assets.coingecko.com/markets/images/866/small/bitmex.jpeg?1706864881",
        has_trading_incentive: false,
        trust_score: 7,
        trust_score_rank: 79,
        trade_volume_24h_btc: 7.242145071565705,
        trade_volume_24h_btc_normalized: 7.242145071565705
    },
    {
        id: "delta_spot",
        name: "Delta Exchange",
        year_established: null,
        country: "Jamaica",
        description: "",
        url: "https://www.delta.exchange/app/spot/trade/",
        image: "https://assets.coingecko.com/markets/images/642/small/delta_spot.jpg?1706864589",
        has_trading_incentive: false,
        trust_score: 7,
        trust_score_rank: 80,
        trade_volume_24h_btc: 5.766980609597685,
        trade_volume_24h_btc_normalized: 5.766980609597685
    },
    {
        id: "bitrue",
        name: "Bitrue",
        year_established: 2018,
        country: "Singapore",
        description: "",
        url: "https://www.bitrue.com/",
        image: "https://assets.coingecko.com/markets/images/254/small/unnamed_%281%29.png?1706864350",
        has_trading_incentive: false,
        trust_score: 6,
        trust_score_rank: 81,
        trade_volume_24h_btc: 39181.9426386503,
        trade_volume_24h_btc_normalized: 17986.485807959758
    },
    {
        id: "uniswap_v3_arbitrum",
        name: "Uniswap V3 (Arbitrum One)",
        year_established: null,
        country: null,
        description: "",
        url: "https://app.uniswap.org/#/swap",
        image: "https://assets.coingecko.com/markets/images/702/small/uniswap-v3.png?1706864655",
        has_trading_incentive: false,
        trust_score: 6,
        trust_score_rank: 82,
        trade_volume_24h_btc: 5406.182168334793,
        trade_volume_24h_btc_normalized: 5406.182168334793
    },
    {
        id: "uniswap_v2",
        name: "Uniswap V2 (Ethereum)",
        year_established: 2018,
        country: null,
        description: "",
        url: "https://app.uniswap.org/#/swap?use=V2",
        image: "https://assets.coingecko.com/markets/images/535/small/256x256_Black-1.png?1706864503",
        has_trading_incentive: false,
        trust_score: 6,
        trust_score_rank: 83,
        trade_volume_24h_btc: 3309.7372428534904,
        trade_volume_24h_btc_normalized: 3309.7372428534904
    },
    {
        id: "weex",
        name: "WEEX",
        year_established: 2018,
        country: "Singapore",
        description:
            'WEEX is a prominent centralized cryptocurrency exchange that was established in 2018 with a $100 million investment from Singapore\'s leading blockchain investment firm. It aims to provide comprehensive and trustworthy services in the cryptocurrency trading field. With low trading fees and user-friendly access, WEEX facilitates the trading of various cryptocurrencies and futures. In addition to spot trading, it also offers options for futures trading and OTC trading, catering to different investment preferences.To prioritize the safety of user funds, WEEX has established a 1000 BTC user protection fund, with the address publicly disclosed to ensure transparency and accountability.  WEEX takes pride in its team members who possess extensive experience in the blockchain industry, coming from reputable institutions such as Wall Street, Silicon Valley, Citibank, Google, and other top-tier financial companies. The management team is globally distributed across Singapore, Taiwan, Dubai, and other locations. Moreover, WEEX holds MSB financial licenses in the U.S. and Canada, an SVGFSA license, as well as the AUSTRAC license in Australia, further bolstering its credibility and compliance with regulatory requirements.  Adhering to a ""customer-first, partner-first"" business philosophy, WEEX Exchange strives to deliver highly secure and all-encompassing cryptocurrency services. By fostering ""win-win cooperation,"" WEEX creates abundant business opportunities for its global partners.',
        url: "http://www.weex.com/",
        image: "https://assets.coingecko.com/markets/images/1398/small/WEEX-icon-200.png?1706865400",
        has_trading_incentive: false,
        trust_score: 6,
        trust_score_rank: 84,
        trade_volume_24h_btc: 2487.3463011656513,
        trade_volume_24h_btc_normalized: 2487.3463011656513
    },
    {
        id: "c_patex",
        name: "C-Patex",
        year_established: null,
        country: "Argentina",
        description: "",
        url: "https://c-patex.com/",
        image: "https://assets.coingecko.com/markets/images/246/small/Exchange.jpg?1706864344",
        has_trading_incentive: false,
        trust_score: 6,
        trust_score_rank: 85,
        trade_volume_24h_btc: 1994.6856979943323,
        trade_volume_24h_btc_normalized: 1994.6856979943323
    },
    {
        id: "coincheck",
        name: "Coincheck",
        year_established: 2014,
        country: "Japan",
        description: null,
        url: "https://coincheck.com/",
        image: "https://assets.coingecko.com/markets/images/18/small/Coincheck.jpg?1706864255",
        has_trading_incentive: null,
        trust_score: 6,
        trust_score_rank: 86,
        trade_volume_24h_btc: 1693.6926252477424,
        trade_volume_24h_btc_normalized: 1693.6926252477424
    },
    {
        id: "icrypex",
        name: "Icrypex",
        year_established: 2018,
        country: "Turkey",
        description:
            "Welcome to ICRYPEX - where the future of finance is being reimagined through cutting-edge cryptocurrency and digital asset solutions. Since our inception in Istanbul in 2018, we have swiftly risen to become Turkey's leading corporate cryptocurrency exchange, serving millions of users, and now set to expand our global footprint. Holding a VASP license in two European Union countries and facilitating EUR, USD, TRY, RUB transfers, and more, ICRYPEX stands at the forefront of the crypto revolution, fostering innovation, accessibility, and trust.   Our foundation rests on innovation and financial responsibility, guiding us to provide a seamless, user-friendly experience while upholding complete transparency. With a robust product range, lightning-fast transactions, and competitively low commissions, ICRYPEX offers a global platform that confidently empowers users to explore the exciting world of digital assets.   At ICRYPEX, we believe in fostering well-informed trades, and in supporting this, we've gathered a team of cryptocurrency experts ready to assist you at any hour. Our commitment to round-the-clock customer support ensures you'll never face the crypto journey alone.   But we're more than just an exchange. ICRYPEX takes pride in giving back to society. We passionately support sports, nurture young athletes, promote education, and raise financial literacy levels, making a meaningful impact on the lives of many.   Trust in Crypto. Speed in Crypto. Transparency in Crypto. Accessibility in Crypto. This is what defines ICRYPEX - where rich opportunities await.   As Turkey's premier corporate cryptocurrency exchange, ICRYPEX is built on a foundation of secure, fast, and reliable trading capabilities, elevating your investment experience to unparalleled heights. Our commitment to global accessibility is evident in our self-managed order books, nodes, and trading and matching engines. We've tailored our platform to host a diverse range of cryptocurrencies, over 168 pairs, from established players like Bitcoin, Ethereum, and Ripple, to ARB, APT, ChainLink, and AVAX.   At ICRYPEX, we believe in personalized service. That's why we stand as Turkey's pioneering exchange with dedicated customer representatives available 24/7. Our goal is to make your journey seamless, whether you're a seasoned investor or just taking your first steps into the crypto realm.   We are driven by the promise of Web 3.0, seeking to empower Turkey's presence in the blockchain universe. With a firm belief in local talent and Turkish capital, we've crafted an infrastructure that's secure, transparent, and fast - all from day one.   ICRYPEX's unwavering commitment to effective communication is showcased in our 24/7 support and transparent auditing practices. As a forward-thinking industry leader, we continually invest in research and development to advance the Turkish cryptocurrency ecosystem and raise blockchain technology awareness throughout the nation.   But our vision doesn't stop at Turkey's borders. ICRYPEX is expanding its global reach, catering to clients of all sizes and locations. From large corporations to small and medium-sized businesses, our platform is designed to meet diverse needs. We offer a customizable white-label solution, allowing large corporations to tailor the platform to their own branding and requirements.   At ICRYPEX, we combine cutting-edge technology with a customer-centric approach, redefining the cryptocurrency trading experience. So come, step into the future of finance, where endless possibilities await. Join us at ICRYPEX, the frontier of innovation in the world of digital assets.",
        url: "https://www.icrypex.com/en",
        image: "https://assets.coingecko.com/markets/images/1222/small/X.png?1706865230",
        has_trading_incentive: false,
        trust_score: 6,
        trust_score_rank: 87,
        trade_volume_24h_btc: 2101.9105114703852,
        trade_volume_24h_btc_normalized: 930.8333291778097
    },
    {
        id: "traderjoe-v2-1-avalanche",
        name: "Trader Joe V2.1 (Avalanche)",
        year_established: null,
        country: null,
        description: "",
        url: "https://traderjoexyz.com/avalanche/trade",
        image: "https://assets.coingecko.com/markets/images/1124/small/JoeToken.png?1706865143",
        has_trading_incentive: false,
        trust_score: 6,
        trust_score_rank: 88,
        trade_volume_24h_btc: 919.6460544186665,
        trade_volume_24h_btc_normalized: 919.6460544186665
    },
    {
        id: "deribit_spot",
        name: "Deribit Spot",
        year_established: 2016,
        country: "Panama",
        description: "",
        url: "https://www.deribit.com/",
        image: "https://assets.coingecko.com/markets/images/1144/small/deribit.jpeg?1706865161",
        has_trading_incentive: false,
        trust_score: 6,
        trust_score_rank: 89,
        trade_volume_24h_btc: 742.9669655647406,
        trade_volume_24h_btc_normalized: 742.9669655647406
    },
    {
        id: "bitcoin_com",
        name: "FMFW.io",
        year_established: 2019,
        country: "Bahamas",
        description:
            "The mission of FMFW.io is to empower people from all over the world to trade cryptocurrencies with ease and confidence, from first-time traders to advanced trading professionals. With high liquidity, 24/7 multilingual support and dozens of trading pairs, complemented with a high level of security, we offer an attractive platform for trading any cryptocurrency. Within one year since launch, on average, our exchange has been visited by more than 500K active traders per month, and this number continues to grow as you read this sentence. \r\n\r\nKey Features:\r\n\r\n- Enjoy more than 130 available trading pairs\r\n- Cutting-edge matching engine technologies\r\n- Up 5x and 10x leverage for more than 29 markets\r\n- Deep liquidity\r\n- User-friendly trading terminal\r\n- Tight spreads\r\n- Consistent trading competitions and giveaways",
        url: "https://fmfw.io/",
        image: "https://assets.coingecko.com/markets/images/467/small/fmfw.png?1706864453",
        has_trading_incentive: false,
        trust_score: 6,
        trust_score_rank: 90,
        trade_volume_24h_btc: 3401.057708610728,
        trade_volume_24h_btc_normalized: 738.2585959331396
    },
    {
        id: "pancakeswap_new",
        name: "PancakeSwap (v2)",
        year_established: 2020,
        country: null,
        description: "",
        url: "https://pancakeswap.finance",
        image: "https://assets.coingecko.com/markets/images/687/small/pancakeswap.jpeg?1706864634",
        has_trading_incentive: false,
        trust_score: 6,
        trust_score_rank: 91,
        trade_volume_24h_btc: 716.0138393887296,
        trade_volume_24h_btc_normalized: 716.0138393887296
    },
    {
        id: "gmo_japan",
        name: "GMO Japan",
        year_established: null,
        country: "Japan",
        description: "",
        url: "https://coin.z.com/jp/",
        image: "https://assets.coingecko.com/markets/images/430/small/gmo_z_com.png?1706864428",
        has_trading_incentive: false,
        trust_score: 6,
        trust_score_rank: 92,
        trade_volume_24h_btc: 485.5294863068164,
        trade_volume_24h_btc_normalized: 485.5294863068164
    },
    {
        id: "catex",
        name: "Catex",
        year_established: 2018,
        country: "China",
        description:
            "Established in August 2018, Catex is a centralized cryptocurrency exchange. It has global communities in Brazil, Vietnam, South Korea, Bangladesh, Russia, Turkey, Middle East, India, Indonesia, and the United States.\r\n\r\nPlatform has staking, farming and multiple faucets.\r\n\r\nThe exchange claims to have SNA and microservice-based distributed architecture to support horizontal scaling.",
        url: "https://www.catex.io/",
        image: "https://assets.coingecko.com/markets/images/354/small/catex.png?1706864384",
        has_trading_incentive: false,
        trust_score: 6,
        trust_score_rank: 93,
        trade_volume_24h_btc: 854.703303498993,
        trade_volume_24h_btc_normalized: 389.8290598273544
    },
    {
        id: "independent_reserve",
        name: "Independent Reserve",
        year_established: 2013,
        country: "Australia",
        description: "",
        url: "https://www.independentreserve.com/",
        image: "https://assets.coingecko.com/markets/images/389/small/x_V5Jquo_400x400.png?1706864404",
        has_trading_incentive: false,
        trust_score: 7,
        trust_score_rank: 94,
        trade_volume_24h_btc: 302.3042098382345,
        trade_volume_24h_btc_normalized: 302.3042098382345
    },
    {
        id: "bcex",
        name: "BCEX",
        year_established: null,
        country: "Hong Kong",
        description: "",
        url: "https://www.bcex.kr/",
        image: "https://assets.coingecko.com/markets/images/190/small/bcex.jpg?1706864323",
        has_trading_incentive: false,
        trust_score: 6,
        trust_score_rank: 95,
        trade_volume_24h_btc: 280.2895254580405,
        trade_volume_24h_btc_normalized: 280.2895254580405
    },
    {
        id: "valr",
        name: "VALR",
        year_established: 2018,
        country: "South Africa",
        description: "",
        url: "https://www.valr.com/",
        image: "https://assets.coingecko.com/markets/images/1036/small/VALR_Logo_%281%29.png?1712145988",
        has_trading_incentive: false,
        trust_score: 6,
        trust_score_rank: 96,
        trade_volume_24h_btc: 201.15333729133408,
        trade_volume_24h_btc_normalized: 201.15333729133408
    },
    {
        id: "qmall",
        name: "QMall",
        year_established: null,
        country: "Lithuania",
        description: "",
        url: "https://qmall.io/",
        image: "https://assets.coingecko.com/markets/images/1108/small/qmall.jpeg?1706865129",
        has_trading_incentive: false,
        trust_score: 6,
        trust_score_rank: 97,
        trade_volume_24h_btc: 3142.8442074823997,
        trade_volume_24h_btc_normalized: 198.81779765168594
    },
    {
        id: "maverick_protocol",
        name: "Maverick Protocol",
        year_established: null,
        country: null,
        description: "",
        url: "https://www.mav.xyz/",
        image: "https://assets.coingecko.com/markets/images/1160/small/maverick.png?1706865175",
        has_trading_incentive: false,
        trust_score: 6,
        trust_score_rank: 98,
        trade_volume_24h_btc: 178.97489167406115,
        trade_volume_24h_btc_normalized: 178.97489167406115
    },
    {
        id: "biswap-v3-1",
        name: "Biswap V3",
        year_established: null,
        country: null,
        description: "",
        url: "https://biswap.org/swap?",
        image: "https://assets.coingecko.com/markets/images/1318/small/biswap.jpeg?1706865322",
        has_trading_incentive: false,
        trust_score: 6,
        trust_score_rank: 99,
        trade_volume_24h_btc: 160.23104337727176,
        trade_volume_24h_btc_normalized: 160.23104337727176
    },
    {
        id: "pancakeswap-v3-opbnb",
        name: "Pancakeswap V3 (opBnb)",
        year_established: null,
        country: null,
        description: "",
        url: "https://pancakeswap.finance/swap",
        image: "https://assets.coingecko.com/markets/images/1294/small/pcs.jpeg?1706865287",
        has_trading_incentive: false,
        trust_score: 6,
        trust_score_rank: 100,
        trade_volume_24h_btc: 129.93798070107874,
        trade_volume_24h_btc_normalized: 129.93798070107874
    }
];
